/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServerHostPortImport } from './routes/server.$host.$port'

// Create Virtual Routes

const DirectViaWsLazyImport = createFileRoute('/direct-via-ws')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DirectViaWsLazyRoute = DirectViaWsLazyImport.update({
  path: '/direct-via-ws',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/direct-via-ws.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ServerHostPortRoute = ServerHostPortImport.update({
  path: '/server/$host/$port',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/direct-via-ws': {
      preLoaderRoute: typeof DirectViaWsLazyImport
      parentRoute: typeof rootRoute
    }
    '/server/$host/$port': {
      preLoaderRoute: typeof ServerHostPortImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  DirectViaWsLazyRoute,
  ServerHostPortRoute,
])

/* prettier-ignore-end */
